name: PHIFURN
layout_spectrum: 0.14540638006292284
typography_spectrum: 0.6704640514217317
cta: {}
analytics: {}
opengraph:
  type: ''
  appId: ''
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.36046511260792613
  lightness: 0.24894020427018404
  saturation: 0.3410606072284281
  rhythmicContrast: 0.18546246131882071
purpose: []
title: learning and building a self reliant life.
author:
  name: 'Aaron Dillon '
  url: ''
  email: moderncavemanoutfitters@gmail.com
content_rating:
  adult: false
